### ISSUE TITLE
show icons when debug is running instead of loading icon ?

### ISSUE THREAD

**Issue by ctf0** [EverlastEngineering/debugInTitlebar#1] opened 2020-12-21 22:47 UTC
so instead of the circling green triangle, the ext check if debug is running and show the icons set directly.

**Comment by EverlastEngineering** [comment] 2020-12-22 14:29
Can you describe what behaviour you see? What you describe is the intended function:

- the play button is present when the debugger is not running. None of the other buttons would be functional at that point, so I decided to hide them to save real estate when not running.
- when you click play it begins the selected debug option from the debug viewlet dropdown
- when the debugger is running, the buttons appears while initializing, greyed out, then light when available.

Do you see something else?

https://user-images.githubusercontent.com/2895375/102898916-369c4380-4438-11eb-9795-c84ba7cd3150.mov

**Comment by ctf0** [comment] 2020-12-22 14:53
what i meant is for the ext to listen to `workbench.action.debug.start` cmnd & based on it we display the debug icons.

so no need for the green triangle at the far top right.

**Comment by DominicVonk** [comment] 2020-12-22 14:57
Yeah @ctf0 I know what you mean, I think it should be an option it the green play button should be visible or not. Because I like this better but not everyone.

**Comment by EverlastEngineering** [comment] 2020-12-22 14:58
Gotcha! One of the use cases for me was to have constant access to the debug start command, no matter what the rest of the interface is showing, so this is by design. Feel free to make a PR to make this a configurable option, that'd be the bet solution imo.

**Comment by EverlastEngineering** [comment] 2020-12-22 15:01
I think this is how it's done?

https://code.visualstudio.com/api/references/contribution-points#contributes.configuration

**Comment by EverlastEngineering** [comment] 2020-12-22 15:03
Lemme have a look now. If I can solve it before my coffee is cold, I'll commit. 👍

**Comment by DominicVonk** [comment] 2020-12-22 15:05
@EverlastEngineering check pr

**Comment by EverlastEngineering** [comment] 2020-12-22 15:06
YAAAAAAS

**Comment by EverlastEngineering** [comment] 2020-12-22 15:06
Beat me to it haha

**Comment by ctf0** [comment] 2020-12-22 15:09
awesome 👯

**Comment by EverlastEngineering** [comment] 2020-12-22 15:28
@DominicVonk your code doesn't work on my machine. There's a missing } and a couple spelling mistakes. I'll commit that now, but it still doesn't read the config in the package.json on my machine.

**Comment by EverlastEngineering** [comment] 2020-12-22 15:30
@DominicVonk I added VSCE_TOKEN as a secret, is that not correct?

**Comment by DominicVonk** [comment] 2020-12-22 15:33
Yes that's correct, it did work, I see there is a small issue with my change let me fix it

**Comment by DominicVonk** [comment] 2020-12-22 15:35
@EverlastEngineering new pr

**Comment by EverlastEngineering** [comment] 2020-12-22 15:49
@DominicVonk yaml build succeeded in publishing 1.0.4 to the store, but exited with a 1 which caused the build the be marked as a fail. Any suggestions? I might remove this for now anyway because I like to test PRs before they get published.

**Comment by EverlastEngineering** [comment] 2020-12-22 15:49
In any case, thanks for the suggestion @ctf0, closing this issue. 1.0.4 is live. Thanks a lot @DominicVonk!

**Closed as completed** 2020-12-22 15:49 UTC

**Comment by DominicVonk** [comment] 2020-12-23 05:15
> @DominicVonk yaml build succeeded in publishing 1.0.4 to the store, but exited with a 1 which caused the build the be marked as a fail. Any suggestions? I might remove this for now anyway because I like to test PRs before they get published.

I will change the publish script to use tags, then it will only publish you tag the version, are you on the vscode slack? https://vscode-dev-community.slack.com/?redir=%2Fmessages%2FC74CB59NE
